### ISSUE TITLE
#02 User Story 2: Spotlight Piece

### ISSUE THREAD

**Issue by StephMode** [StephMode/art-gallery-app#2]
**Value Proposition**

As an art enthusiast

I want to see a spotlight piece

so that I can get inspirational highlights.

**Acceptance Criteria**

[ ]     One art piece is picked at random to show as a spotlight piece
[ ]     The art piece image is displayed
[ ]     The art piece artist is displayed

**Tasks**

- [x] Write function to pick one art piece [at random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#examples)
- [x] Create the component Spotlight
- [x] Spotlight props: image, artist

**Comment by StephMode** [comment]
Action Plan:

- [ ] Create the Comp Spotlight (child of HomePage)
- [ ] Give comp the props image, artist
- [ ] Make it render one artwork from the API using notation but hard coded using pieces prop

**Comment by StephMode** [comment]
Took me about 1,5 h to complete

Major challenges were:
- determining where to integrate the component in the app structure
- creating the indexing using MathRandom (MathRandom I knew, but not had too much exp with)

Final solution in a nutshell:
- Spotlight has to be child of HomePage because it shall be rendered as the homepage from user POV (refer to wireframes)
- MathFloor MathRandom logic had the be in HomePage, since {pieces} of HomePage grants access to the data of the fetch
- Spotlight only needs to take random indices as props in HomePage, and inside the rcf 

Notes on action planning and reasoning:

Develop Spotlight comp to show one art piece at random

First Approach:

- make it child of HomePage and use pieces comp to pull data

xx> 🟡 passing down of data works, but I don't see how I can use props image, artist there there

Second Approach

- make it child of ArtPieces
so that it can make use of pieces and can call it's own props

xx> 🟡 could work technically, but from a component structure perspective, it doesn'T make to much sense
!!> 🟡 look at the wireframes again: the Spotlight is the HOMEPAGE, hence the comp should rather be child of homepage

Third Approach

✅ - make it child of HomePage after all
✅ - MathRandom should be implemented in HomePage where we have access to the data
✅ - call props image, artist in spotlight
✅ - MathRandom shall then be stored in a variable so that it can be accessed as an index to the props
✅ - props will then pass down randomized index of artist and imageSource as props in the comp
✅ - Spotlight shall than serve as purely represenational component
